swagger: '2.0'
info:
  version: '1.0.0'
  title: Radio Interface ptls-comm
  description: An API that exposes data for a radio channel.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: roip-interface-ch1ch2:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /channels:
    get:
      description: Returns all pets from the system that the user has access to
      produces:
        - application/json
      responses:
        '200':
          description: channel response
          schema:
            type: array
            items:
              $ref: '#/definitions/channel'
        default:
          description: unexpected error
  /channels/{channelInternalName}:
    get:
      description: Returns the channel identified by the given name
      produces:
        - application/json
      parameters:
        - name: channelInternalName
          in: path
          description: Name of channel to fetch
          required: true
          type: string
      responses:
        '200':
          description: channel response
          schema:
            $ref: '#/definitions/channel'
        '400':
          description: parameter invalid
        '404':
          description: channel not found
        default:
          description: unexpected error
  /channels/{channelInternalName}/transmissionStart:
    put:
      description: Activates the radio device for a transmission. On digital radio devices where a timeslot has to be assigned prior to the transmission, this is done before returning a status code. If a timeslot cannot be assigned, the code 503 is returned.
      parameters:
        - name: channelInternalName
          in: path
          description: Name of channel to activate
          required: true
          type: string
      responses:
        '204':
          description: now transmitting
        '400':
          description: parameter invalid
        '404':
          description: channel not found
        '503':
          description: channel occupied
        default:
          description: unexpected error
  /channels/{channelInternalName}/transmissionStop:
    put:
      description: Deactivates the radio device for a transmission
      parameters:
        - name: channelInternalName
          in: path
          description: Name of channel to deactivate
          required: true
          type: string
      responses:
        '204':
          description: Successful set
        '400':
          description: parameter invalid
        '404':
          description: channel not found
        default:
          description: unexpected error
definitions:
  channel:
    type: object
    properties:
      channelInternalName:
        type: string
      gpioOutPtt:
        type: integer
        format: int32
      gpioInSquelch:
        type: integer
        format: int32
      audioOutDevice:
        type: string
      audioOutChannel:
        type: string
      audioInDevice:
        type: string
      audioInChannel:
        type: string

